spring:
  application:
    name: eureka-service

server:
  port: 8761
  enableSelfPreservation: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health